### ISSUE TITLE
epub mobi file cannot GetPixmap() or GetText()

### ISSUE THREAD

**Issue by aslyr2024** [ArtifexSoftware/MuPDF.NET#140]
![image](https://github.com/user-attachments/assets/36287e06-e2e7-457a-88f8-9d67186f2ac3)

Document doc = new Document(@"1.epub");
doc[0].GetText();
var toc= doc.GetToc();
var bmp= doc[0].GetPixmap();
bmp.Save("d:/1.jpg");

warning: dropping unclosed output
Unhandled exception. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at mupdf.mupdfPINVOKE.fz_save_pixmap_as_jpeg(HandleRef jarg1, String jarg2, Int32 jarg3)
   at mupdf.mupdf.fz_save_pixmap_as_jpeg(FzPixmap pixmap, String filename, Int32 quality)
   at MuPDF.NET.Pixmap.WriteImage(String filename, Int32 format, Int32 jpgQuality)
   at MuPDF.NET.Pixmap.Save(String filename, String output, Int32 jpgQuality)
   at Program.<Main>$(String[] args) in C:\code\MuPDF.NET-main\Examples\TextboxExtraction\CSharp\Program.cs:line 8

but  mupdfcore and pymupdf can do this well

**Comment by green0317** [comment]
Hi @aslyr2024 , pymupdf and mupdf.net are using same api and same logic. but mupdf.net has some kinds of problems with epub format obviously, I think that must be fixed and sharing sample epub file will be helpful.

**Comment by aslyr2024** [comment]
[https://github.com/ArtifexSoftware/MuPDF.NET/blob/main/MuPDF.NET.Test/resources/Bezier.epub](url)
this project test epub also cannot open

**Comment by aslyr2024** [comment]
Document doc = new Document(@"C:\code\MuPDF.NET-main\MuPDF.NET.Test\resources\Bezier.epub");
	doc[0].GetText();
	var toc = doc.GetToc();
	var bmp = doc[0].GetPixmap();
	bmp.Save("d:/1.jpg");

<html>
<body>

External component has thrown an exception.
--
RuntimeMethodInfo•••mupdfPINVOKE.fz_save_pixmap_as_jpeg (HandleRef jarg1, String jarg2, Int32 jarg3) | RuntimeMethodInfo••• | mupdfPINVOKE.fz_save_pixmap_as_jpeg (HandleRef jarg1, String jarg2, Int32 jarg3)
RuntimeMethodInfo•••
mupdfPINVOKE.fz_save_pixmap_as_jpeg (HandleRef jarg1, String jarg2, Int32 jarg3)
External component has thrown an exception.
(0 items) | (0 items)
(0 items)
null
null
MuPDF.NET
-2147467259
at mupdf.mupdfPINVOKE.fz_save_pixmap_as_jpeg(HandleRef jarg1, String jarg2, Int32 jarg3)   at mupdf.mupdf.fz_save_pixmap_as_jpeg(FzPixmap pixmap, String filename, Int32 quality)   at MuPDF.NET.Pixmap.WriteImage(String filename, Int32 format, Int32 jpgQuality)   at MuPDF.NET.Pixmap.Save(String filename, String output, Int32 jpgQuality)   at UserQuery.Main(), line 9
-2147467259


</body>
</html>

**Comment by green0317** [comment]
Maybe there seems to be some updates in `doc open` feature on mupdf.
MuPDF.NET uses mupdf dev-version later than pymupdf uses, so that may has such issues.
we need to wait for fix on mupdf.
